@extends('layouts.public')
@section('title', 'Privacy — Parallel Leaves')
@section('content')
<article class="section shell legal"><p class="eyebrow">YOUR WORK, HANDLED WITH CARE</p><h1>Privacy notice.</h1><p class="legal-date">Effective September 8, 2026</p><p class="intro">{{ config('public.operator') }}, {{ config('public.location') }}, operates Parallel Leaves. This notice explains the information used to provide your translation workspace and how to contact us about it.</p>
<h2>1. Information we process</h2><p>Account data includes your username, email address, password hash, and account/session identifiers. If you sign in with Google, we receive account information such as your Google identifier, email, display name, and profile image. Passwords are stored as hashes.</p><p>Workspace data includes manuscripts, source and translated text, chapter structure, book details, covers, Codex and style content, dictionary entries, translation memory, prompts, and model settings. We also store the API key you provide so the server can make the AI requests you choose to run. BYOK does not mean your key remains only in your browser.</p>
<h2>2. Why we use it</h2><p>We use this information to create and maintain accounts, authenticate access, send password recovery emails, store and edit books, generate AI-assisted output, export your work, respond to support requests, diagnose errors, and protect the service. Account information needed for registration is required to provide an account; AI credentials are needed for the features that use your provider.</p>
<h2>3. External providers and international processing</h2><p>When you run language-model features, text, instructions, and selected context are sent through OpenRouter to the chosen model provider. Depending on the feature and your settings, context may include chapter text, Codex, dictionary, or translation-memory examples. Cover-generation requests use external image services, including fal.ai. Only use these tools with content you are permitted to send for processing.</p><p>Google handles Google sign-in, if you choose it. Mailgun processes account email delivery, including recipient email addresses and password-reset messages. Hosting and operational providers may process data to deliver the service. These providers may process data outside Taiwan and your country; their policies and settings govern their own retention and use. This notice does not promise that every provider has the same training or retention policy.</p>
<h2>4. Storage, logs, and browser information</h2><p>Workspace and account data are stored on the service's systems. AI request and response logs can contain prompts, manuscript passages, and generated text. Translation logs can contain source/target text and model information. Authorized administration and support may access information as needed for operations and assistance.</p><p>The app uses session and security cookies for authentication and browser storage for preferences such as theme and language. These support the workspace experience. This public-page redesign does not add advertising trackers or marketing analytics.</p>
<h2>5. Retention and deletion</h2><p>Book data remains stored so you can continue your work. You can delete books through the workspace and request account or personal-data deletion through support. Operational logs, backups, and provider-held copies may be retained separately; deleting a book does not necessarily remove all such copies immediately. Contact us for the retention details relevant to your request. We may need to retain information to meet legal obligations, resolve disputes, or protect the service.</p>
<h2>6. Your choices and requests</h2><p>You may request access to or a copy of your personal data, corrections, cessation of collection/processing/use, or deletion, subject to applicable law. Email <a href="mailto:{{ config('public.support_email') }}">{{ config('public.support_email') }}</a> and describe your request. We may need to verify your identity before acting. Do not email your password or API key.</p><p>You can download your translated manuscript as DOCX, your translation memory as custom XML, and a complete book archive containing readable data and available cover files. You may choose to edit manually without running AI features. Revoking a key at your provider prevents further use of that key.</p>
<h2>7. Security and changes</h2><p>Keep your password unique and your provider key private. No online service can promise absolute security. Contact us promptly if you believe your account or data has been accessed without permission. We may update this notice as the service changes and will show a revised effective date.</p><p>Privacy contact: <a href="mailto:{{ config('public.support_email') }}">{{ config('public.support_email') }}</a><br>{{ config('public.operator') }} · {{ config('public.location') }}</p></article>
@endsection
