@extends('layouts.public')
@section('title', 'Terms & conditions — Parallel Leaves')
@section('content')
<article class="section shell legal"><p class="eyebrow">THE WORKSPACE AGREEMENT</p><h1>Terms & conditions.</h1><p class="legal-date">Effective September 8, 2026</p><p class="intro">Parallel Leaves is operated by {{ config('public.operator') }}, {{ config('public.location') }}. These terms explain the basis on which we provide the service.</p>
<h2>1. Using the service</h2><p>By creating an account or using Parallel Leaves, you agree to these terms. You must be legally able to enter this agreement, or have the permission required by applicable law. Keep your account information accurate, protect your credentials, and contact us if you suspect unauthorized access.</p>
<h2>2. Your content and rights</h2><p>You retain the rights you hold in your manuscripts, translations, and other content. You give us permission to store, process, and transmit that content as needed to provide the features you use. This permission does not transfer ownership of your work to us. You are responsible for having the rights or permission needed to upload, translate, process, and share material, including through external AI services.</p>
<h2>3. Human review and AI services</h2><p>AI output can be inaccurate, incomplete, inconsistent, or similar to other material. Review outputs before using or publishing them. Parallel Leaves does not guarantee translation accuracy, originality, suitability, or rights clearance. Features using external providers are also subject to those providers' terms and availability.</p>
<h2>4. Free access and planned subscriptions</h2><p>All current app features are free to use. The displayed USD $19 monthly and USD $199 yearly plans are placeholders for future pricing. There is no active paid subscription or automatic conversion from free access. Any future paid subscription will require a separate opt-in with its pricing and billing terms presented at that time.</p><p>AI usage through your own API key may be charged separately by your provider. These charges are your responsibility and are not included in the planned Parallel Leaves subscription prices. Monitor your provider's usage and billing settings.</p>
<h2>5. Acceptable use</h2><p>Do not use the service unlawfully, infringe others' rights, distribute malicious code, attempt unauthorized access, or disrupt the service. We may restrict or suspend access where reasonably necessary to address abuse, security concerns, or legal obligations.</p>
<h2>6. Export and account closure</h2><p>You can export translated manuscripts, translation memory, and book archives using the available tools. Keep copies of important work. For account closure or personal-data requests, contact <a href="mailto:{{ config('public.support_email') }}">{{ config('public.support_email') }}</a>. See our <a href="/privacy">Privacy notice</a> for more information about retained data.</p>
<h2>7. Availability and responsibility</h2><p>We may maintain, update, or discontinue parts of the service. Availability and uninterrupted access are not guaranteed. To the extent allowed by applicable law, the service is provided as available without warranties, and we are not responsible for indirect or consequential losses arising from its use. Nothing in these terms excludes rights or liabilities that cannot lawfully be excluded.</p>
<h2>8. Changes, governing law, and contact</h2><p>We may update these terms and will indicate the effective date. Material changes will be communicated through the service or an appropriate account contact channel. These terms are governed by the laws of Taiwan, subject to any mandatory protections that apply to you.</p><p>{{ config('public.operator') }} · {{ config('public.location') }}<br>Questions: <a href="mailto:{{ config('public.support_email') }}">{{ config('public.support_email') }}</a></p></article>
@endsection
